### ISSUE TITLE
provider requirements declaration missing from the main module

### ISSUE THREAD

**Issue by jghal** [terraform-aws-modules/terraform-aws-network-firewall#10]
## Description

This was already described fairly well in #3 but the issue was never acknowledged and was closed automatically by a bot.

- [x] ✋ I have searched the open/closed issues and my issue _is listed but closed without acknowledgement or comment._

## Versions

- Module version [Required]:

- Terraform version:
- Provider version(s):
```bash
$ terraform version
Terraform v1.12.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.78.0
```

## Reproduction Code [Required]

Define an aliased provider and call this module

```hcl
provider "aws" {
  region = "us-west-1"
  alias  = "west"
}

module "network_firewall" {
  source = "terraform-aws-modules/network-firewall/aws"
  version = "~> 1.0.0"
  providers = {
    aws = aws.west
  }
}
```

then run `terraform init`

## Expected behavior

```
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/network-firewall/aws 1.0.2 for network_firewall...
- network_firewall in .terraform/modules/network_firewall
- network_firewall.firewall in .terraform/modules/network_firewall/modules/firewall
- network_firewall.policy in .terraform/modules/network_firewall/modules/policy
Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v6.4.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

## Actual behavior

```
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/network-firewall/aws 1.0.2 for network_firewall...
- network_firewall in .terraform/modules/network_firewall
- network_firewall.firewall in .terraform/modules/network_firewall/modules/firewall
- network_firewall.policy in .terraform/modules/network_firewall/modules/policy
Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 5.2.0"...
- Installing hashicorp/aws v6.4.0...
- Installed hashicorp/aws v6.4.0 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Reference to undefined provider
│ 
│   on main.tf line 213, in module "network_firewall":
│  213:     aws = aws.west
│ 
│ There is no explicit declaration for local provider name "aws" in module.network_firewall, so Terraform is assuming you mean
│ to pass a configuration for "hashicorp/aws".
│ 
│ If you also control the child module, add a required_providers entry named "aws" with the source address "hashicorp/aws".
│ 
│ (and one more similar warning elsewhere)
╵
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

## Additional context

This is discussed [here](https://discuss.hashicorp.com/t/no-explicit-declaration-for-local-provider/67828/2) by HashiCorp developer that modules are expected to define their provider requirements.

**Comment by bryantbiggs** [comment]
> This was already described fairly well in https://github.com/terraform-aws-modules/terraform-aws-network-firewall/issues/3 but the issue was never acknowledged and was closed automatically by a bot.

<img width="695" height="132" alt="Image" src="https://github.com/user-attachments/assets/bc48837e-abdd-4cde-80d3-7fffdbc5aa64" />

**Comment by bryantbiggs** [comment]
Why is the aliased provider necessary?

**Comment by jghal** [comment]
Our code requires multiple AWS providers to be defined. So don't make use of a default unaliased provider, forcing every resource to explicitly set the correct provider.

**Comment by bryantbiggs** [comment]
the root module does not use any resource directly hence why we do not have any required providers - the required providers are defined where resources are used. we are explicit about this

**Comment by bryantbiggs** [comment]
what Martin is talking about is something entirely different - you do not have to define providers provided by Hashicorp since Terraform will automatically resolve those. but any 3rd party providers you are required to define those. 

that is not the case here

**Comment by jghal** [comment]
The linked discussion is about passing an aliased aws provider into a module with no provider declared, and the warning is verbatim the same as what I've posted here and was described in #3. I don't see how it can be interpreted as a different scenario or how Martin's comments don't apply here.

Regardless, how do you suggest we get rid of the warning when using your module with aliased providers? Which of my providers will the module use if I don't tell it?

**Comment by bryantbiggs** [comment]
this is what that linked discussion is about - https://registry.terraform.io/modules/bryantbiggs/sans-provider/aws/latest

```hcl
module "sans_provider" {
  source = "bryantbiggs/sans-provider/aws"

  tags = {
    Terraform   = "true"
    Environment = "dev"
  }
}
```

try it - it works, and yet no AWS provider is explicitly declared despite their being an `aws_*` resource. Should you do this - no. You should define a required provider (typically min version supported) for each provider used by the resources. This is what we do. 

However, the root module here does not have any bare resources - it only contains definitions for local modules, which said local modules DO have their necessary required versions because that is where the resources are define

**Comment by jghal** [comment]
I understand the point you're making that you don't want to specify a provider in the main module because it doesn't directly declare any `aws` provider resources. But it's still the case that including your module with an aliased provider passed to it produces a warning.

Yes, if I don't pass a provider into the main firewall module, the warning goes away. But I don't have an `aws` provider defined without an alias. _All_ my `aws` providers have an alias. So I don't know which provider your module is going to use unless I explicitly tell it which one, as described in the [Terraform documentation for using modules.](https://developer.hashicorp.com/terraform/language/modules/develop/providers#passing-providers-explicitly). But as soon as I do that, I get the warning.

So again, if you're not going to add the provider declaration to your main module, how are developers who have to use an aliased provider supposed to include your main module without getting a warning? And yes, I know the code will still apply correctly with the warning. But why not fix the warning when it's such an innocuous change in the code?

**Comment by jghal** [comment]
@bryantbiggs is there any suggestion for resolving the warning when using the main module with an aliased provider? I don't like leaving fixable warnings in code, because then people get complacent with not really reading them when looking at pipeline logs and miss other things that pop up later.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.0.0 :tada:

**Comment by jghal** [comment]
@bryantbiggs Adding a region argument neither addresses nor resolves the issue at all. The warning is still present with 2.0 because there is still no provider declaration in the module. The issue is that sometimes we have to use aliased providers, meaning we have to pass a provider argument to your module, and your module does not include a provider declaration, so Terraform issues a warning. Different regions aren't the only reason to have multiple providers. They could be for completely different accounts. But the reason for having multiple aliased providers is completely inconsequential to the issue. So as far as I am aware, the _only_ thing that will resolve the warning for people who are passing a provider into this module is for the module to have a provider dependency declaration.

```bash
$ terraform init -backend=false
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/network-firewall/aws 2.0.0 for network_firewall...
- network_firewall in .terraform/modules/network_firewall
- network_firewall.firewall in .terraform/modules/network_firewall/modules/firewall
- network_firewall.policy in .terraform/modules/network_firewall/modules/policy
Downloading registry.terraform.io/terraform-aws-modules/network-firewall/aws 2.0.0 for network_firewall_rule_group_stateful...
- network_firewall_rule_group_stateful in .terraform/modules/network_firewall_rule_group_stateful/modules/rule-group
Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 6.5.0"...
- Installing hashicorp/aws v6.5.0...
- Installed hashicorp/aws v6.5.0 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Reference to undefined provider
│ 
│   on net.tf line 303, in module "network_firewall":
│  303:     aws = aws.NewAccount
│ 
│ There is no explicit declaration for local provider name "aws" in module.network_firewall, so Terraform is assuming
│ you mean to pass a configuration for "hashicorp/aws".
│ 
│ If you also control the child module, add a required_providers entry named "aws" with the source address
│ "hashicorp/aws".
│ 
│ (and one more similar warning elsewhere)
╵
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
 I tried changing qualifying the passed provider like with variations of this, including quotes (both single and double):

```hcl
module "network_firewall" {
  source = "terraform-aws-modules/network-firewall/aws"
  version = "~> 2.0.0"

  providers = {
    hashicorp/aws = aws.NewAccount
  }

....
}
```

And every variation produces a syntax error in the init.

```bash
$ terraform init -backend=false
Initializing modules...
╷
│ Error: Invalid provider configuration reference
│ 
│   on net.tf line 303, in module "network_firewall":
│  303:     hashicorp/aws = aws.NewAccount
│ 
│ The providers argument requires a provider type name, optionally followed by a period and then a configuration
│ alias.
```

As I said in the PR I opened, just adding the provider declaration to the versions.tf for the module in the .terraform folder gets rid of the warning.

```bash
$ cat .terraform/modules/network_firewall/versions.tf 
terraform {
  required_version = ">= 1.5.7"
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}
$ terraform init -backend=false
Initializing modules...
Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v6.5.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

If you know of another way to pass an aliased provider into the module without getting a warning, I would be happy to test it out.

**Comment by bryantbiggs** [comment]
It's literally why the region argument was added to the provider. Don't use the aliased provider, just specify the region
